CREATE TABLE IF NOT EXISTS `tbl_disaster` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `reference_id` varchar(50) NOT NULL,
  `incident_category` varchar(50) NOT NULL,
  `disaster_type` varchar(100) NOT NULL,
  `incident_date` date NOT NULL,
  `incident_time` time NOT NULL,
  `location` varchar(255) NOT NULL,
  `severity` varchar(20) NOT NULL,
  `description` text NOT NULL,
  `students_affected` int(11) DEFAULT 0,
  `staff_affected` int(11) DEFAULT 0,
  `casualty_details` text DEFAULT NULL,
  `property_damage` text DEFAULT NULL,
  `evacuation_status` varchar(50) DEFAULT NULL,
  `suspension_status` varchar(50) DEFAULT NULL,
  `uploaded_photos` text DEFAULT NULL,
  `school_name` varchar(255) NOT NULL,
  `school_address` varchar(255) DEFAULT NULL,
  `reporter_name` varchar(255) NOT NULL,
  `contact_number` varchar(50) NOT NULL,
  `email_address` varchar(100) DEFAULT NULL,
  `additional_info` text DEFAULT NULL,
  `date_submitted` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `reference_id` (`reference_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
